version: '3'

services:
  db:
    restart: always
    container_name: db
    image: postgres:13.1
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - dbdata:/var/lib/postgresql/data/

  django_backend:
    container_name: django-backend
    build:
     context: .
     dockerfile: Dockerfile
    # entrypoint: /entrypoint.sh
    # command: bash -c "python manage.py runserver 0.0.0.0:${DJANGO_PORT}"
    environment:
     POSTGRES_NAME: ${POSTGRES_NAME}
     POSTGRES_LOCAL_PORT: ${POSTGRES_LOCAL_PORT}
     POSTGRES_PORT: ${POSTGRES_LOCAL_PORT}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
     POSTGRES_HOST: db

    expose:
     - "${DJANGO_PORT}"
    volumes:
     - .:/django_app
     - static_volume:/app/public/static
     - media_volume:/app/public/media
    depends_on:
     - db
    restart: on-failure

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/public/static
      - media_volume:/app/public/media

    ports:
      - "8080:80"
    depends_on:
      - django_backend

volumes:
  dbdata:
  static_volume:
  media_volume: